services:
  portal-proxy:
    image: hub.cangling.cn/cangling/nginx-rtmp:v4.2.33
    restart: unless-stopped
    ports:
      - "7700:80"
      - "7701:81"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - ./nginx/logs:/var/logs/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/var/www/html
    networks:
      - np4-network

  portal-server:
    image: hub.cangling.cn/cangling/gwt-template:latest
    expose:
      - "8080"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - ./dev/data/app.json:/root/mapway/app.json
      - app-volume:/data/dev
      - /opt:/cangling-apps
    networks:
      - np4-network
    depends_on:
      - portal-db

  portal-db:
    image: hub.cangling.cn/cangling/postgis:17
    networks:
      - np4-network
    volumes:
      - postgis-volume:/var/lib/postgresql/data
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    expose:
      - "5432"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  portal-openldap:
    image: hub.cangling.cn/cangling/openldap:final
    user: "0:0"
    ports:
      - "389:1389"
    environment:
      - LDAP_ROOT=dc=tjj,dc=cn
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=Openldap2025*
      - LDAP_USERS=zhangjianshe
      - LDAP_PASSWORDS=Zhangjianshe2025*
    volumes:
      - ./data/ldap:/bitnami/openldap
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    networks:
      - np4-network

networks:
  np4-network:
    external: true

volumes:
  postgis-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: './dev/postgis'
  app-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: './dev/data'