package cn.mapway.gwt_template.client.workspace.widget;

public enum ActionMenuKind {
    AMK_ADD_GROUP,
    AMK_ADD_MEMBER,
    AMK_EDIT_GROUP,
    AMK_DELETE, EXPORT_TO_PICTURE, ZOOM_TO_FIT, AMK_EDIT_TASK, AMK_CREATE_TASK, AMK_CREATE_SUB_TASK, AMK_DELETE_TASK, AMK_EXPORT_PICTURE, AMK_EXPORT_TASK, AMK_TIP, AMK_CREATE_DIRFILE, AMK_CREATE_RESOURCE, AMK_DELETE_RESOURCE, AMK_DELETE_DIRFILE, AMK_UPLOAD_DIRFILE, AMK_IMPORT_TASK
}
