<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>index</title>
    <script src="/js/app/app.nocache.js?r=${timestamp}"></script>
    <link rel="stylesheet" href="/css/main.css"/>
    <style>

        @font-face {
            font-family: 'Iosevka';
            src: url(./webfonts/iosevka.woff2) format('woff2'),
            url(./webfonts/iosevka.woff) format('woff');
            font-display: swap;
            font-weight: normal;
            font-style: normal;
        }

        @font-face {
            font-family: "mapway-font";
            font-style: normal;
            font-weight: 400;
            src: url(./webfonts/iconfont.woff2) format('woff2');
        }

        body {
            margin: 0px;
            padding: 0px;
            box-sizing: border-box;
        }
    </style>
</head>
<body>

</body>
</html>